# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./generator
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: generator/package-lock.json
        node-version: '22.x'
        cache: 'npm'
    - run: npm ci
    - run: npm run generate

    - name: Deploy to Server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.6
      with:
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        server: ${{ secrets.FTP_HOST }}
        port: ${{ secrets.FTP_PORT }}
        local_path: './public/*'
        remote_path: '/'
        sftp_only: true
        sftpArgs: '-o ConnectTimeout=5'